GET localhost:8080/api/user/me
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6Imd3ZWhqIiwiZW1haWwiOiJnd2VoakBnbWFpbC5jb20iLCJleHAiOjE3MjMyOTg2OTAsIm5iZiI6MTcyMzI5ODU3MCwiaWF0IjoxNzIzMjk4NTcwfQ.FnKPfhdH58g_y6QUc3GH_FhGG6s_z785Vk0g9_rrHbQ
